hook.Add( "PopulateToolMenu", "SimpleWeaponSwayOptions", function()
    spawnmenu.AddToolMenuOption( "Options", "Simple Weapon Sway", "Simple Weapon Sway", "Server Settings", "", "", function( panel )
        if LocalPlayer():IsAdmin() then
        panel:NumSlider( "Max Breath", "sws_maxbreath", 1, 100, 0 )
        panel:ControlHelp( "Maximum ammount of breath time (in seconds)" )
        panel:NumSlider( "Damage Sway Speed", "sws_swayspeed", 0.1, 10, 1 )
        panel:ControlHelp( "Controls sway speed while you took damage" )
        panel:NumSlider( "Damage Sway Amount", "sws_swayamount", 0.01, 1, 2 )
        panel:ControlHelp( "Amount of sway while you took damage" )
        panel:NumSlider( "Breath Sway Amount", "sws_breathswayamount", 0.001, 0.01, 3 )
        panel:ControlHelp( "Amount of sway while you are aiming" )
        panel:NumSlider( "Breath Sway Speed", "sws_breathswayspeed", 0.1, 10, 1 )
        panel:ControlHelp( "Amount of sway speed while you are aiming" )
        panel:NumSlider( "Damage Sway Time", "sws_damagecooldown", 1, 100, 0 )
        panel:ControlHelp( "Controls the time the Damage Sway will be active after taking damage" )
        local updateButton = vgui.Create("DButton", panel)
            updateButton:SetText("Update Convars")
            updateButton:SetPos(55, 380)
            updateButton:SetSize(200, 20) 
            updateButton.DoClick = function()
                RunConsoleCommand("sws_update_convars")
            end
        end
    end)
end)
